### ISSUE TITLE
does not run on RHEL6: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by smkr** [willthames/ansible-inventory-grapher#15]
This is really simple to report :)

```python
$ ansible-inventory-grapher -h
Traceback (most recent call last):
  File "/usr/bin/ansible-inventory-grapher", line 25, in <module>
    import ansibleinventorygrapher
  File "/usr/lib/python2.6/site-packages/ansibleinventorygrapher/__init__.py", line 107
    nodes = {Node(host.name, vars=vars[host], leaf=True)}
                                                        ^
SyntaxError: invalid syntax
```

Hopefully it is a simple answer. Thanks!

**Comment by willthames** [comment]
Ah, it appears I've used the set constructor that only appears in python 2.7 which isn't installed on RHEL6.

**Comment by willthames** [comment]
@smkr this is a duplicate of #13. 

This was fixed in version 1.0.2, and version 1.0.3 is available through pip. 

Are you able to update through pip or are you relying on RPMs?

**Comment by smkr** [comment]
Wow, that's fast! Thanks willthames! Yes, unfortunately I do rely on RPMs as I'm running Ansible from a central box. As a workaround I cloned the repo on my F21 workstation. If it can be updated in EPEL it'd be great though as I'm sort of stuck with RHEL6 for now.

**Comment by FlorianHeigl** [comment]
It seems to be still b0rked in EPEL, don't know how to change that.

**Comment by willthames** [comment]
Submitted https://bugzilla.redhat.com/show_bug.cgi?id=1384253 to request an upgrade.
