### ISSUE TITLE
TypeError on run with ansible 2.0.2.0

### ISSUE THREAD

**Issue by opoplawski** [willthames/ansible-inventory-grapher#18]
```
# ansible-inventory-grapher webserver
Traceback (most recent call last):
  File "/bin/ansible-inventory-grapher", line 128, in <module>
    main()
  File "/bin/ansible-inventory-grapher", line 124, in main
    render_graph(arg, options)
  File "/bin/ansible-inventory-grapher", line 88, in render_graph
    inventory = ansible.inventory.Inventory(options.inventory)
TypeError: __init__() takes at least 3 arguments (2 given)
```

**Comment by willthames** [comment]
What version of ansible-inventory-grapher are you using?

It should all work with Ansible 2.0 if you're using ansible-inventory-grapher 2.0.0 or above (but 2.1.0 is better if you're still using Ansible 1.9)

```
$ ansible-inventory-grapher --version
ansible-inventory-grapher 2.1.0
```

**Comment by opoplawski** [comment]
Seems to be working now.

ansible-inventory-grapher-2.3.2-1.el7.noarch
ansible-2.2.1.0-1.el7.noarch
