### ISSUE TITLE
cannot import name PromptVaultPass

### ISSUE THREAD

**Issue by jacobweber** [willthames/ansible-inventory-grapher#31]
Getting this error on Mac OS 10.13.1, with ansible 2.4.1 and python 2.7.10, when using --ask-vault-pass:

```
$ ansible-inventory-grapher -i /path/to/hosts --ask-vault-pass \*

Traceback (most recent call last):
  File "/usr/local/bin/ansible-inventory-grapher", line 154, in <module>
    main()
  File "/usr/local/bin/ansible-inventory-grapher", line 150, in main
    render_graph(arg, options)
  File "/usr/local/bin/ansible-inventory-grapher", line 109, in render_graph
    inventory_mgr = ansibleinventorygrapher.inventory.InventoryManager(options.inventory, options.ask_vault_pass, options.vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 158, in __init__
    self.inventory = INVENTORY(inventory, ask_vault_pass, vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 104, in __init__
    super(Inventory24, self).__init__(inventory, ask_vault_pass, vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 24, in __init__
    self.vault_pass = self.ask_vault_password()
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 98, in ask_vault_password
    from ansible.parsing.vault import PromptVaultPass
ImportError: cannot import name PromptVaultPass
```

**Comment by willthames** [comment]
Fixes pushed to v2.4.3
