### ISSUE TITLE
unbound method _read_file() must be called with FileVaultSecret instance as first argument

### ISSUE THREAD

**Issue by jacobweber** [willthames/ansible-inventory-grapher#32]
Getting this error on Mac OS 10.13.1, with ansible 2.4.1 and python 2.7.10, when using --vault-password-file:

```
$ ansible-inventory-grapher -i /path/to/hosts --vault-password-file=pass.txt \*

Traceback (most recent call last):
  File "/usr/local/bin/ansible-inventory-grapher", line 154, in <module>
    main()
  File "/usr/local/bin/ansible-inventory-grapher", line 150, in main
    render_graph(arg, options)
  File "/usr/local/bin/ansible-inventory-grapher", line 109, in render_graph
    inventory_mgr = ansibleinventorygrapher.inventory.InventoryManager(options.inventory, options.ask_vault_pass, options.vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 158, in __init__
    self.inventory = INVENTORY(inventory, ask_vault_pass, vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 104, in __init__
    super(Inventory24, self).__init__(inventory, ask_vault_pass, vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 26, in __init__
    self.vault_pass = self.read_vault_password_file(vault_password_file)
TypeError: unbound method _read_file() must be called with FileVaultSecret instance as first argument (got str instance instead)
```

**Comment by willthames** [comment]
Fixes pushed to v2.4.3
