### ISSUE TITLE
Decryption failed on vault file

### ISSUE THREAD

**Issue by jacobweber** [willthames/ansible-inventory-grapher#33]
I tried downgrading from Ansible 2.4 to 2.2, since I was having issues with the vault command (#31, #32). I got past those errors, but now it's unable to decrypt the vault file. This is on Mac OS 10.13.1, with ansible 2.2.0.0 and python 2.7.10, when using --ask-vault-pass:

```
$ ansible-inventory-grapher -i /path/to/hosts --ask-vault-pass \*

Vault password: <entered password>
Traceback (most recent call last):
  File "/usr/local/bin/ansible-inventory-grapher", line 154, in <module>
    main()
  File "/usr/local/bin/ansible-inventory-grapher", line 150, in main
    render_graph(arg, options)
  File "/usr/local/bin/ansible-inventory-grapher", line 109, in render_graph
    inventory_mgr = ansibleinventorygrapher.inventory.InventoryManager(options.inventory, options.ask_vault_pass, options.vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 158, in __init__
    self.inventory = INVENTORY(inventory, ask_vault_pass, vault_password_file)
  File "/Library/Python/2.7/site-packages/ansibleinventorygrapher/inventory.py", line 73, in __init__
    host_list=inventory)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 97, in __init__
    self.parse_inventory(host_list)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 164, in parse_inventory
    group.vars = combine_vars(group.vars, self.get_group_variables(group.name))
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 554, in get_group_variables
    self._vars_per_group[groupname] = self._get_group_variables(groupname, vault_password=vault_password)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 572, in _get_group_variables
    vars = combine_vars(vars, self.get_group_vars(group))
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 774, in get_group_vars
    return self._get_hostgroup_vars(host=None, group=group, new_pb_basedir=new_pb_basedir, return_results=return_results)
  File "/Library/Python/2.7/site-packages/ansible/inventory/__init__.py", line 835, in _get_hostgroup_vars
    host_results = self._variable_manager.add_group_vars_file(base_path, self._loader)
  File "/Library/Python/2.7/site-packages/ansible/vars/__init__.py", line 615, in add_group_vars_file
    data = self._load_inventory_file(path, loader)
  File "/Library/Python/2.7/site-packages/ansible/vars/__init__.py", line 553, in _load_inventory_file
    results = self._load_inventory_file(path=p, loader=loader)
  File "/Library/Python/2.7/site-packages/ansible/vars/__init__.py", line 568, in _load_inventory_file
    data = loader.load_from_file(path)
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 119, in load_from_file
    (file_data, show_content) = self._get_file_contents(file_name)
  File "/Library/Python/2.7/site-packages/ansible/parsing/dataloader.py", line 178, in _get_file_contents
    data = self._vault.decrypt(data, filename=b_file_name)
  File "/Library/Python/2.7/site-packages/ansible/parsing/vault/__init__.py", line 264, in decrypt
    raise AnsibleError(msg)
ansible.errors.AnsibleError: Decryption failed on /path/to/secret.yml
```

However, when I ran this on the same file, and entered the same password, it was able to display the file:
```
ansible-vault view --ask-vault-pass /path/to/secret.yml
```

**Comment by willthames** [comment]
Fixes pushed to v2.4.3

**Comment by jacobweber** [comment]
Thanks for the quick fix. However, I'm now getting the message "Couldn't find a secret to decrypt vaulted file(s)", when I use either `--ask-vault-pass` or `--vault-password-file`.

**Comment by willthames** [comment]
Is this still with Ansible 2.2?

Might be worth just raising a new Issue for this as it's now a different bug (oops). I did try and test several scenarios but might have missed one (or more)

**Comment by willthames** [comment]
OK, I found it with some manual runs (the automated tests don't cover that what the command line options are supposed to receive is what is actually passed). 

This will be fixed with 2.4.4

**Comment by willthames** [comment]
v2.4.4 pushed to PyPI and Github

**Comment by jacobweber** [comment]
Hmm, unfortunately it's still giving me the same error (on ansible 2.2 at least). I opened #35.
